### PR TITLE
separating perf-test to 2 jobs: trigger job prepares Windup, matrix job runs Windup on test apps

### PR DESCRIPTION
**Pull request by OndrejKotek**

### CODE REVIEW

**Comment by d-s** [comment]
Thanks Ondrej! @mareknovotny can you take a look?

**Comment by mareknovotny** [comment]
@OndrejKotek from my point of view it looks good. Would you like to continue on this PR to finish it? I would assume as yes. If not just let me know.

I looked through 2 new CI jobs for using this and looks good too.

**Comment by OndrejKotek** [comment]
@mareknovotny I would like to have this PR merged and the jobs used "in production" at first. I do not know how much time I (will) have to improve `Main.groovy`.

**Comment by mareknovotny** [comment]
ok np, just keep both old and new CI for a moment in parallel ;)

**Pull request merged**
